app:
  port: 8001
  ws:
    prefix-channel: "channel-"
    prefix-channel-history: "channel-history-"
    max-history-life-time-in-seconds: 5
    max-connection-time-in-seconds: 180

server:
  port: ${app.port}

management:
  endpoint:
    health:
      show-details: always
