app:
  port: 8000
  ws:
    prefix-channel: "channel-"
    prefix-channel-history: "channel-history-"
    prefix-connection-queue: "connection-"
    keepalive-timeout-in-seconds: 30

server:
  port: ${app.port}

management:
  endpoint:
    health:
      show-details: always